### ISSUE TITLE
Skip classes by Attribute

### ISSUE THREAD

**Issue by OskarStark** [TomasVotruba/class-leak#10]
The `symfony/messenger` uses an attribute `#[AsMessageHandler]`. If this attribute is used and/or `MessageHandlerInterface` is implemented, the class should not be marked as _leaked_

What about having specific rule sets for frameworks like Symfony and Laravel?

**Comment by TomasVotruba** [comment]
Hi, this makes sense. If class contains one of specific list of attributes, it should be skipped :+1:

**Comment by TomasVotruba** [comment]
Closing for lack of feedback, to keep issue tracker focus on unclear issues that needs our attention.

Feel free to send PR with the reproducer :+1:

Thank you for understanding :slightly_smiling_face:

**Comment by ruudk** [comment]
Implemented in https://github.com/TomasVotruba/class-leak/pull/33
