### ISSUE TITLE
Allow to specify directory/namespace

### ISSUE THREAD

**Issue by OskarStark** [TomasVotruba/class-leak#11]
It could be helpful to not just skip a single type, but a whole directory or namespace.

In my case I have a folder with generated classes for fields based on some CSV input. Those field classes can then be used by a developer in the future, but are not all used yet.

**Comment by TomasVotruba** [comment]
Hi, by convention this and other public classes, e. g. in open-source packages, should be marked with `@api`. 
Those are skipped by class leak. As there is already convention for this and suits your case, better use the one.
