### ISSUE TITLE
ignore paths

### ISSUE THREAD

**Issue by staabm** [TomasVotruba/class-leak#14]
in our project we want to analyze certain paths, but not some of the subpaths included in them

e.g. analyze `library/` and all its subfolders but not `library/FolderToIgnore/`

**Comment by TomasVotruba** [comment]
Hi, based on few months of usage, this could lead to quite complex setup of add/ignore filtering.
The package should be lean and slim instead, so I won't be adding these. 

Thanks for understanding :+1:
