### ISSUE TITLE
".72" releases are preferred over normal ones

### ISSUE THREAD

**Issue by szepeviktor** [TomasVotruba/class-leak#18]
.72 releases include `"php": ">=7.2"`
Users on PHP 8+ will always install this because its semver is higher than normal releases.
It should include `"php": ">=7.2 <8.1"` to prevent that.

**Comment by szepeviktor** [comment]
I do not dare to send a PR because of fear of closure.
https://github.com/TomasVotruba/class-leak/blob/7cdda3da30699d63e4fe67e0ac1b9258ae45f828/build/target-repository/composer.json#L6

**Comment by TomasVotruba** [comment]
This is intended, as 7.2 package is also scoped.
