### ISSUE TITLE
global namespaced classes

### ISSUE THREAD

**Issue by staabm** [TomasVotruba/class-leak#22]
it seems classes which are defined in the global namespace are not found, as the source of truth are the "use" statements, which global classes don't necessarily have

**Comment by TomasVotruba** [comment]
As I see value in having a global class check, the focus of this package is on a modern code base using at least PSR-4.
Checking every name and type could be quite complex and I want to keep this package slim to use and maintain.

Yet, if you find a smart way to detect global classes, feel free to send PR :+1: 

Thanks
