### ISSUE TITLE
wrongly prefixed classes in PossiblyUnusedClassesFilter

### ISSUE THREAD

**Issue by staabm** [TomasVotruba/class-leak#29]
after installing the tool with `composer require tomasvotruba/class-leak --dev` open  the file

`vendor/tomasvotruba/class-leak/src/Filtering/PossiblyUnusedClassesFilter.php` and find wrongly-prefixed code in the static `DEFAULT_TYPES_TO_SKIP`-array

![grafik](https://github.com/TomasVotruba/class-leak/assets/120441/0650a615-4426-40fc-953a-4413d62eb60e)

which effectively makes the default-types-to-skip useless

**Comment by TomasVotruba** [comment]
Thanks for reporting :+1: 

Fixed i nhttps://github.com/TomasVotruba/class-leak/commit/0ae12dad605894c1aed03b61479960d4394ae651
