### ISSUE TITLE
Word of advise for Laravel users

### ISSUE THREAD

**Issue by szepeviktor** [TomasVotruba/class-leak#4]
The Laravel Framework uses classes automatically.
One example is listener discovery.
https://laravel.com/docs/10.x/events#event-discovery

Could you add a section to README?

**Comment by szepeviktor** [comment]
Another example: https://laravel.com/docs/10.x/authorization#policy-auto-discovery

**Comment by TomasVotruba** [comment]
This would make README full of all frameworks :) instead this should be handled internally for the user.

**Comment by szepeviktor** [comment]
> Could you make test fixture and prepare fix?

No. I do not know how to do that.
