### ISSUE TITLE
Warn on skipped but non-leaked classes

### ISSUE THREAD

**Issue by szepeviktor** [TomasVotruba/class-leak#6]
Let's say I skip a class that is referenced in the code.
`vendor/bin/class-leak check src/ --skip-type 'A\Referenced\Class'`
It would be nice to get a warning about it.

**Comment by TomasVotruba** [comment]
I don't get this one. Could you share an example?

**Comment by szepeviktor** [comment]
1. You skip a class because it is really unused
2. You begin using that class
3. Run the same `class-leak` command again
4. Get a warning that the above mentioned skipped class is no unused

**Comment by TomasVotruba** [comment]
Ah, I see. Like reporting unnecesary ignores :) 

Feel free to contribute, if you like :+1:
